/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f5faf8",
        surface: "#f5faf8",
        "surface-dim": "#d6dbd9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f5f2",
        "surface-container": "#eaefed",
        "surface-container-high": "#e4e9e7",
        "surface-container-highest": "#dee4e1",
        "surface-bright": "#f5faf8",
        "surface-variant": "#dee4e1",
        primary: "#00685f",
        "on-primary": "#ffffff",
        "primary-container": "#008378",
        "on-primary-container": "#f4fffc",
        "primary-fixed": "#89f5e7",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        "primary-fixed-dim": "#6bd8cb",
        "inverse-primary": "#6bd8cb",
        "surface-tint": "#006a61",
        secondary: "#006e2f",
        "on-secondary": "#ffffff",
        "secondary-container": "#6bff8f",
        "on-secondary-container": "#007432",
        "secondary-fixed": "#6bff8f",
        "on-secondary-fixed": "#002109",
        "on-secondary-fixed-variant": "#005321",
        "secondary-fixed-dim": "#4ae176",
        tertiary: "#825100",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a36700",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-fixed-dim": "#ffb95f",
        "outline-variant": "#bcc9c6",
        outline: "#6d7a77",
        "on-surface": "#171d1c",
        "on-surface-variant": "#3d4947",
        "on-background": "#171d1c",
        "inverse-surface": "#2c3130",
        "inverse-on-surface": "#edf2f0",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["1.125rem", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        base: "8px",
        "margin-mobile": "16px",
        lg: "40px",
        sm: "12px",
        gutter: "24px",
        "margin-desktop": "48px",
        "container-max": "1280px",
        md: "24px",
        xs: "4px",
        xl: "64px",
        "2xl": "96px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        ambient: "0 4px 20px -2px rgba(0, 104, 95, 0.08), 0 0 3px rgba(0, 104, 95, 0.04)",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      keyframes: {
        scan: {
          "0%": { transform: "translateY(0)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateY(100px)", opacity: "0" },
        },
      },
      animation: {
        scan: "scan 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
